name: 📝 Documentation Update
description: Suggest what documentation should be updated/changed
title: 'docs: '
labels: ['🔬 documentation']
body:
  - type: textarea
    attributes:
      label: Is your documentation change request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. Ex. I'd like to change the following things [...]
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like to see
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Describe alternate solutions
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other information related to the feature here. If your feature request is related to any issues or discussions, link them here.
